### ISSUE TITLE
Reupload des gesamten Projekts

### ISSUE THREAD

**Issue by fo-code** [ob-algdati-ws17/blatt-7-aufgabe-1-jo-code-fo-code#1]
Sehr geehrter Herr Braun,
leider haben wir anfangs das .gitignore vergessen und daher .idea etc. hochgeladen, was ja nicht hochgeladen werden soll, da dort u.a. das persönliche Workspace-Directory drin steht.
Damit diese Informationen nicht öffentlich sind, haben wir die entsprechenden commits gelöscht, alles davor als Zip gespeichert und anschließend nur die benötigten Files/Ordner reuploaded.
Aufgrund dessen fehlen jetzt die ersten commits, in denen wir das Projekt und die Googletests eingerichtet haben. 
Daher wollten wir fragen, ob dies ein Problem darstellt für die Bewertung.

Mit freundlichen Grüßen

**Comment by obcode** [comment]
nein. Kein Problem. Aber bestimmt ein guter Lerneffekt ;-)

Hatte mir schon überlegt, statt dem leeren Repo eine `.gitignore` als Startercode zur Verfügung zu stellen 😄

**Comment by fo-code** [comment]
Das auf alle Fälle, vielen Dank für die schnelle Antwort :)
